spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    #解决could not initialize proxy - no Session
    properties:
      hibernate.enable_lazy_load_no_trans: true

  #解决数据某个字段为null时不显示
  jackson:
    default-property-inclusion: non_null

#url前缀
server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n "
#  #path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.jianpan.sell.app.LoggerTest: debug


wechat:
  mpAppId: wx4e7096883b4d0464
  mpAppSecret: ff4067fbb9f20e16b5edbf5bb253ed0c